# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dde506073855b3891301afe4dc9879bacf57f958aa410bb0706d19e5fe4969c9be013afc53db1cdd2b35d8d4535cbd63a82e54e527c11de783e207a46b2f357

test:
  secret_key_base: 46189dd0347fc681fd4a548d7c280fd7ba159438200e05440353cf7aa1659fe2018d27117357f2e978fc51a512fe5a10b56df7e3a2ca7b6c14cb76f97da07aac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
